[".var/app/com.github.wwmm.easyeffects/config/easyeffects/output"]
  type = "archive"
  url = "https://github.com/JackHack96/EasyEffects-Presets/archive/refs/heads/master.zip"
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/*.json"]

[".var/app/com.github.wwmm.easyeffects/config/easyeffects"]
  type = "archive"
  url = "https://github.com/JackHack96/EasyEffects-Presets/archive/refs/heads/master.zip"
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/irs/*.irs"]